#define KEY_Q 1
#define KEY_W 2
#define KEY_E 3
#define KEY_R 4
#define KEY_T 5
#define KEY_Y 6
#define KEY_U 7
#define KEY_I 8
#define KEY_O 9
#define KEY_P 10
#define KEY_A 11
#define KEY_S 12
#define KEY_D 13
#define KEY_F 14
#define KEY_G 15
#define KEY_H 16
#define KEY_J 17
#define KEY_K 18
#define KEY_L 19
#define KEY_Z 20
#define KEY_X 21
#define KEY_C 22
#define KEY_V 23
#define KEY_B 24
#define KEY_N 25
#define KEY_M 26
